### ISSUE TITLE
Enable https on notesfrombelow.org

### ISSUE THREAD

**Issue by georgeowell** [dellsystem/notes-from-below#52]
It would be great to enable TLS/https on the site so that people can connect securely. You can easily get free certificates from Lets Encrypt using [CertBot](https://certbot.eff.org/) :closed_lock_with_key: :heart: Let me know if there's anything I can do to help with that.

All the best!

**Comment by dellsystem** [comment]
It should be enabled right now via CloudFlare (which is admittedly imperfect). Does it work for you? https://notesfrombelow.org

**Comment by georgeowell** [comment]
Yep, work for me! Agree on CloudFlare, they're not great. Closing.
